Allow writing a NRRD record to memory. Ref #108
mhe/pynrrd pull request #117
Opened 2022-06-11 21:42 UTC by bernardopericacho

## Proposed changes:

- `write` now supports as a parameter either a filename or a `io.BytesIO` object.
- refactor write method into:
   - `_write_default_header_entries` to write the default header entries generated by this package
   - `_handle_header_fields` to determine the headers based on the specified headers, data and index order
   - `_write_header` that used the logic from `_write_default_header_entries` and `_handle_header_fields` to write the headers
   - `write` used the methods above to encapsulate and reuse better the code
   - added new tests to check the functionality. Coverage still 100% after these changes

2022-06-14 14:41 UTC, addisonElliott requested changes

2022-06-14 14:44 UTC, addisonElliott commented
One more thing. Can you add examples for reading and writing to memory? That's probably useful to demonstrate.

2022-06-17 00:09 UTC, bernardopericacho commented
I think I addressed all the feedback if you can have another look. Thanks in advance!

2022-06-17 00:37 UTC, addisonElliott approved these changes

2022-06-17 00:37 UTC, merged